# docker-compose.yml
version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: portfolio_db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: portfolio
      MYSQL_USER: system
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  app:
    build: .
    ports:
      - "80:80"
    restart: "always"

volumes:
  mysql-data: